#!/usr/bin/env python3
"""Derive the TMLR submission (tmlr-article.tex) from the Springer source.

Source: ../sn-article-template/sn-article.tex (the sn-jnl version, single
source of truth for the prose, figures, tables and bibliography).

What changes: the sn-jnl scaffolding (class, title/author/abstract/keywords
macros, \botrule, the appendices environment, the Springer back matter) is
replaced by the TMLR one; \cite becomes natbib author-year (\citep, with the
handful of textual uses turned into \citet/\citealp/\citealt); the
bibliography moves before the appendix as in the TMLR template; a Broader
Impact Statement and a Reproducibility paragraph replace the Springer
declarations; "our fork" of Propulate becomes "a fork" for double-blind
review; and TMLR_ONLY adds the framing sentences for TMLR's audience (the
simulation-based-inference umbrella, sequential neural SBI and synchronous
SGD as fellow barrier-payers, the baseline-class scoping). Nothing else in
the prose is touched.

Every targeted rewrite asserts that its anchor occurs exactly once in the
source, so an edit to the Springer file that moves or removes an anchor
fails this script instead of silently producing a wrong TMLR version.

Usage: python3 make_tmlr_version.py   (writes tmlr-article.tex next to it)
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent / "sn-article-template" / "sn-article.tex"
TARGET = HERE / "tmlr-article.tex"

PREAMBLE_HEAD = r"""% TMLR version of the paper.
% GENERATED by make_tmlr_version.py from ../sn-article-template/sn-article.tex.
% Edit the Springer source (or the script), then re-run the script; do not
% edit this file by hand unless you intend to fork it.
\documentclass[10pt]{article}
\usepackage{tmlr}
% Camera-ready: \usepackage[accepted]{tmlr}   (also set \month, \year, \openreview below)
% Preprint (de-anonymized, no TMLR mentions): \usepackage[preprint]{tmlr}

\usepackage{graphicx}
\usepackage{amsmath,amssymb,amsfonts}
\usepackage{amsthm}
\usepackage{xcolor}
\usepackage{booktabs}
\usepackage{array}
\usepackage{algorithm}
\usepackage{algorithmicx}
\usepackage{algpseudocode}
\usepackage{hyperref}
\usepackage{url}
\hypersetup{colorlinks=true,allcolors=blue!55!black}
"""

AUTHOR_BLOCK = r"""% Authors are hidden while the tmlr package is used without [accepted]/[preprint].
\author{\name First Author \email first.author@example.com \\
      \addr Department, Organization, City, Country
      \AND
      \name Second Author \email second.author@example.com \\
      \addr Department, Organization, City, Country}

\def\month{MM}  % camera-ready only
\def\year{YYYY} % camera-ready only
\def\openreview{\url{https://openreview.net/forum?id=XXXX}} % camera-ready only
"""

BACK_MATTER = r"""\subsubsection*{Broader Impact Statement}
This work is methodology for likelihood-free inference on parallel machines. Its direct effect is on compute: it removes the idle time a generation barrier imposes on heterogeneous simulator workloads, and the prediction of \S\ref{sec:results-barrier} lets a practitioner estimate that saving from their own timing data before spending an allocation. We see no risk specific to the method beyond those of Bayesian inference in general.

\subsubsection*{Reproducibility}
The repository accompanying this paper contains the summary data behind every figure and table, the scripts that regenerate each from the campaign output, and the committed output of every diagnostic quoted in the text, so every figure, table and quoted number can be regenerated from the repository alone. The full implementation (the Propulate propagator, the matched-kernel pyABC baseline, the analysis and plotting scripts, and the test suite), the raw per-particle records (${\approx}30$\,GB for the Gaussian-mean campaign alone), the per-rank timing logs and the resolved run configurations will be released publicly upon publication.

% TMLR: add these only once the submission is accepted and de-anonymized.
% \subsubsection*{Author Contributions}
% \subsubsection*{Acknowledgments}

\bibliography{references}
\bibliographystyle{tmlr}

\appendix
"""

# (anchor, replacement) pairs applied after the global \cite -> \citep pass;
# each anchor must occur exactly once.
CITATION_FIXES = [
    (
        r"(ABC-SMC \citep{sisson2007,toni2009abcsmc}, ABC-PMC \citep{beaumont2009adaptive}, and adaptive variants \citep{delmoral2012adaptive,drovandi2011,lenormand2013apmc})",
        r"(ABC-SMC, \citealp{sisson2007,toni2009abcsmc}; ABC-PMC, \citealp{beaumont2009adaptive}; adaptive variants, \citealp{delmoral2012adaptive,drovandi2011,lenormand2013apmc})",
    ),
    (
        r"(the balance heuristic of \citep{veach1995})",
        r"(the balance heuristic of \citealt{veach1995})",
    ),
    (
        r"surveyed in \citep{bugallo2017ais}",
        r"surveyed by \citet{bugallo2017ais}",
    ),
    (
        r"\citep{cornuet2012amis}'s convergence argument is heuristic, and \citep{marin2019consistency} restricts",
        r"the convergence argument of \citet{cornuet2012amis} is heuristic, and \citet{marin2019consistency} restrict",
    ),
]

TEXT_FIXES = [
    # double-blind: do not claim ownership of the Propulate fork
    ("in our fork of Propulate", "in a fork of Propulate"),
]

# Framing for TMLR's audience, applied after the citation conversion (anchors
# are therefore in \citep form). Absent from the Springer version by design:
# it situates the paper among sequential neural SBI and asynchronous SGD, which
# a Statistics and Computing reader does not need.
TMLR_ONLY = [
    (
        r"Approximate Bayesian computation (ABC) is the standard route to Bayesian inference when a simulator can be run but its likelihood cannot be evaluated \citep{beaumont2019abc}.",
        r"Approximate Bayesian computation (ABC) is the classical route to simulation-based inference \citep{cranmer2020frontier}: Bayesian inference when a simulator can be run but its likelihood cannot be evaluated \citep{beaumont2019abc}.",
    ),
    (
        "parallelize \\emph{simulation} effectively within a generation.\n",
        "parallelize \\emph{simulation} effectively within a generation.\n\n"
        r"Sequential neural simulation-based inference \citep{papamakarios2016snpe,greenberg2019apt,lueckmann2021benchmark} also proceeds in rounds, each of which simulates a batch from the current proposal and retrains before the next is proposed, so every round waits for its slowest simulation as a generation does. Its barrier cost is of the same kind, set by the runtime distribution and the worker count; the generation-free sampler we propose is specific to ABC. The same wait is the straggler problem of synchronous stochastic gradient descent \citep{dean2012distbelief,chen2016revisiting}, met there with backup workers or with asynchronous, staleness-tolerant updates \citep{recht2011hogwild}. Here the reported estimator is defined on whatever history has arrived, and the order of arrival enters the analysis only through the filtration and fidelity assumptions of \S\ref{sec:theory}."
        "\n",
    ),
    (
        r"All arms run over MPI on JUWELS (Appendix~\ref{app:protocol}).",
        r"All arms run over MPI on JUWELS (Appendix~\ref{app:protocol}). All three comparators are samplers of the same estimator class; a neural simulation-based-inference baseline would change the estimator rather than the barrier, and its rounds would wait for their slowest simulation as generations do (\S\ref{sec:background}).",
    ),
]


def replace_once(text: str, old: str, new: str, what: str) -> str:
    n = text.count(old)
    if n != 1:
        raise SystemExit(f"{what}: expected exactly one occurrence of {old!r}, found {n}")
    return text.replace(old, new)


def sub_once(text: str, pattern: str, repl: str, what: str, flags: int = re.M) -> str:
    text, n = re.subn(pattern, repl, text, flags=flags)
    if n != 1:
        raise SystemExit(f"{what}: expected exactly one match of /{pattern}/, found {n}")
    return text


def main() -> None:
    src = SOURCE.read_text(encoding="utf-8")

    pre, body = src.split(r"\begin{document}", 1)
    body, tail = body.rsplit(r"\end{document}", 1)
    if tail.strip():
        raise SystemExit(f"unexpected text after \\end{{document}}: {tail.strip()[:80]!r}")

    # --- macros and theorem environments defined in the Springer preamble carry over
    carried = [
        line for line in pre.splitlines()
        if re.match(r"\\(newcommand|renewcommand|providecommand|newtheorem|theoremstyle|DeclareMathOperator)\b", line)
    ]
    if not any("newtheorem" in line for line in carried):
        raise SystemExit("no \\newtheorem lines found in the Springer preamble")

    # --- title, authors, abstract, keywords, \maketitle come out of the body
    m = re.search(r"^\\title\[[^\]]*\]\{(.+)\}[ \t]*$", body, re.M)
    if m is None:
        raise SystemExit("could not find \\title[short]{long} in the source")
    title = m.group(1)
    body = body[: m.start()] + body[m.end():]

    body, n_auth = re.subn(r"^\\(author|affil)\*?\[.*$\n?", "", body, flags=re.M)
    if n_auth < 1:
        raise SystemExit("no \\author/\\affil lines found")

    m = re.search(r"^\\abstract\{(.*)\}[ \t]*$", body, re.M)
    if m is None:
        raise SystemExit("could not find the one-line \\abstract{...}")
    abstract = m.group(1)
    body = body[: m.start()] + body[m.end():]

    body = sub_once(body, r"^\\keywords\{.*\}[ \t]*$\n?", "", "keywords")
    body = sub_once(body, r"^\\maketitle[ \t]*$\n?", "", "maketitle")

    # --- citations: natbib author-year
    body, n_cites = re.subn(r"\\cite(?=[\[{])", r"\\citep", body)
    for old, new in CITATION_FIXES:
        body = replace_once(body, old, new, "citation fix")

    # --- tables
    body, n_botrule = re.subn(r"\\botrule\b", r"\\bottomrule", body)
    if n_botrule < 1:
        raise SystemExit("no \\botrule found; has the table format changed?")

    # --- back matter: Springer acknowledgments + declarations -> TMLR sections,
    #     bibliography before the appendix, \appendix instead of the appendices env
    i = body.index(replace_once(body, r"\bmhead{Acknowledgments}", r"\bmhead{Acknowledgments}", "bmhead") and r"\bmhead{Acknowledgments}")
    j = body.index(replace_once(body, r"\begin{appendices}", r"\begin{appendices}", "appendices") and r"\begin{appendices}")
    if not i < j:
        raise SystemExit("acknowledgments must precede the appendices")
    body = body[:i] + BACK_MATTER + body[j + len(r"\begin{appendices}"):]
    body = replace_once(body, "\\end{appendices}\n", "", "end appendices")
    body = replace_once(body, "\\bibliography{sn-bibliography}\n", "", "springer bibliography")

    for old, new in TEXT_FIXES:
        body = replace_once(body, old, new, "text fix")
    for old, new in TMLR_ONLY:
        body = replace_once(body, old, new, "TMLR-only framing")

    leftovers = sorted(set(re.findall(r"\\(?:bmhead|botrule|fnm|sur|affil|orgname|orgdiv|keywords|backmatter)\b", body)))
    if leftovers:
        raise SystemExit(f"sn-jnl macros left in the body: {leftovers}")

    out = (
        PREAMBLE_HEAD
        + "\n"
        + "\n".join(carried)
        + "\n\n"
        + "\\title{" + title + "}\n\n"
        + AUTHOR_BLOCK
        + "\n\\begin{document}\n\n\\maketitle\n\n"
        + "\\begin{abstract}\n" + abstract + "\n\\end{abstract}\n\n"
        + body.strip("\n")
        + "\n\n\\end{document}\n"
    )
    out = re.sub(r"\n{3,}", "\n\n", out)
    TARGET.write_text(out, encoding="utf-8")
    print(
        f"wrote {TARGET.name}: {len(out.splitlines())} lines; "
        f"{n_cites} \\cite -> \\citep ({len(CITATION_FIXES)} textual fixes), "
        f"{n_botrule} \\botrule -> \\bottomrule, {n_auth} author/affil lines dropped, "
        f"{len(carried)} preamble macro lines carried over"
    )


if __name__ == "__main__":
    main()
